### ISSUE TITLE
Compatablility?

### ISSUE THREAD

**Issue by PlayerEpic76** [LOSYandex/angrybirdschrome-source-html5#1]
I am glad to see the revival! anyways, is it possible, by copying over files, to make angry birds wonderful pistachioes compatable?

**Comment by angrybirds-s4uk** [comment]
Hello, idk. The pistachios themselves with angry birds are on the Internet
separately, but about the compatibility of Chrome and Pistachios, if you
just try.

пт, 21 окт. 2022 г. в 02:59, PlayerEpic86 ***@***.***>:
